### ISSUE TITLE
First release TODO

### ISSUE THREAD

**Issue by knuxify** [aspinwall-ui/aspinwall-shell#2]
* [ ] Finish control center
    * [ ] Wire up power button
    * [ ] Wire up settings button
  * [ ] Bluez interface
  * [ ] Screen brightness control
  * [ ] Screen rotation control
    * [ ] Better handling for changing screen sizes 
  * ...and fix pretty much everything. Notification popups are broken, window positioning when launched as an actual session is broken, etc etc.

I'm considering switching the WM to i3 if herbstluftwm doesn't work out; this partially solves our issue with wayland/x11 support, since the WM configs would be the same for i3 and sway. Alternatively, we could still roll our own WM, but whether I'll have the time for that - only time can tell.
